name: Build and deploy cheat sheet

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./src/index.html
          outputFile: ./build/Plotly_Express_cheatsheet.pdf
          pdfOptions: '{"printBackground": true}'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
